# -*- coding: utf-8 -*-
"""modulo1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDI_WPi__kpqYrDJ6OpuaHaeIwRTCrHi

# 🔹 TEMA 1: VARIABLES Y TIPOS DE DATOS
## 🧠 ¿Qué es una variable?

Una variable es un nombre que se le da a un espacio en la memoria para guardar un valor.

**Ejemplo:**
"""



masa = 5.0  # Esto guarda el valor 5.0 en la variable llamada "masa"
print(masa)

bernardo= 7998465
bernardo
gato='es negro'

print(gato)

"""## 🎯 Tipos de datos más comunes:
`int`: números enteros → 10, -3

`float`: números decimales → 3.14, -9.8

`str`: texto → "Física", 'Hola'

`bool`: valores lógicos → True, False

Ejemplo:
"""

nombre = "Isaac Newton"    #Tipo str
edad = 84                 # Tipo int
masa = 70.5               # Tipo float
es_cientifico = True      # Tipo bool

"""y para mostrar, en la pantalla o el output como le dicen los conocedores:"""

print(type(nombre))  # Salida: <class 'str'>
print(nombre)

"""# Ejercicios

Crea las siguientes variables(llenelos con los datos de su conocimiento):

* nombre del cientifico

* masa (kg)

* altura (m)

* planeta (texto)

* gravedad (float)
"""

Nombre_cientifico = "Ramon y Cajal"
masamio = 60
mitalla = 1.73
planeta = "Jupiter"
gravedad = 9.58
print("el cientifico de la neurociencia es:", Nombre_cientifico)
print("tengo un peso de:", masamio, "y mi talla es:",mitalla)
#y asi con los demas

"""Ejercicio 2: Calcular el peso de un objeto, que se da por la siguiente ecuacion:
$$p=m \cdot g$$
donde $p$ es peso, $m$ es la masa (el de un cerebro 🧠 es de $5 [Kg]$) y $g$ es la gravedad que es igual a $g=9.98 [\frac{m}{s^2}]$
"""

#me creo mis variables
m=3.5 #masa del cerebro
g=9.98 #gravedad
p=m*g
print("el peso de un cerebro es de:",p)

"""🧪 Ejercicio 3: Formatear una salida"""

print("El peso del objeto es:", masa * gravedad, "N")

print(f"El peso del objeto es: {masa * gravedad} N")

"""#🔹 TEMA 2: OPERACIONES MATEMÁTICAS BÁSICAS

🧠 ¿Qué son?

Son las operaciones aritméticas que Python puede realizar directamente con variables numéricas `(int, float)`.

##⚙️ Operadores Matemáticos en Python
| Operador | Significado          | Ejemplo (a = 2, b = 3) | Resultado |
|----------|-----------------------|-------------------------|-----------|
| +        | Suma                  | a + b                   | 5         |
| -        | Resta                 | a - b                   | -1        |
| * | Multiplicación        | a * b                   | 6         |
| /        | División              | a / b                   | 0.6667    |
| //       | División entera       | a // b                  | 0         |
| %        | Módulo (residuo)      | a % b                   | 2         |
| ** | Exponente (potencia)  | a ** b                  | 8         |

#ejercicio de ejemplo 🐱
se tiene dos gato alex pesa 5 kg y tony pesa 2.5 kg, cuanto pesaran ambos, para que los lleve en mi mochilla? 💰

$$5+2.5=7.5 [Kg]$$
"""

alex=5
tony=2.5
gt=alex+tony
print("^w^ estos gatos juntos pesan:", gt)

"""#ejericio de emjemplo xd 🧑
si yo que peso 80 kilos y hago ejercicio y pierdo 20 kilos en una semana, cuantos kilos tengo? ☕
"""

kg=80
perdida=20
pesoactual=80-20
print("adelgaze:",pesoactual,"kilitos")

"""#ejercicio de ejemplo 🍫
si como 100 manzanas y 30 mandarinas, 50 chocolates, 20 helados ksjsjsjs 😸
cuantos objetos comi en total??
"""

man=100
mandi=30
choco=50
hell=20
to=man+mandi+choco+hell
print("OMG COMI TANTOOO:",to, "objetos!!!! xdxd")

"""suma de palabras xd"""

num='holi'
num2='crayoli'
num3=num + num2
num3

"""### ejercicios

1.Calcula la energía potencial: $$Ep = m * g * h$$
donde m=78 Kg, g=9.98 $m/s^2$, h=3 m
"""

m=78
g=9.98
h=3
Ep=m*g*h
print("La energia potencial es de:", Ep)

"""2. Suma de dos velocidades: v1 + v2
donde v1=30.8 m/s y v2=68.5 m/s
"""

v1=30.8
v2=68.5
Vt=v1+v2
print("la velocidad total es de:",Vt)

"""3. División para obtener densidad: $$ρ = m / V$$
donde m=70 Kilogramos, V=450 $m^3$
"""

m=70
V=450
densidad=m/V
print("la densidad es:",densidad)

"""Calcular la aceleración media: $$a = \frac{v_{final} - v_{inicial}}{t}$$
sean las velocidades v1 y v2, dichas previamente, con un tiempo de 50 segundos
"""

t=50
a=(v1-v2)/t
print("la aceleracion media es:",a)

"""4. Calcular el volumen de un cubo: $$V = l^3$$
si su lado es de 3 metros
"""

l=3
v=l**3
print("el volumen del cubo es de:",v,"m3")

"""5. Calcular área de un círculo: $$A = π ⋅ r^{2}$$ (usar π = 3.1416) y radio de r= 83.5 metros"""

pi=3.1416
r = 83.5
area=pi*r**2
print("el area es de:", area)

"""6. Calcular el periodo de un péndulo simple: $$T = 2 ⋅ π ⋅ \sqrt{\frac{l}{g}}$$
usa sqrt(x) = `x**0.5`, sabiendo que l=3 metros; g=9.98 m/s^2
"""

l=3
T=2*pi*(3/g)**0.5
print("el periodo es de:",T)

"""### haremos enfasis en lo que es el algoritmo:
*Un algoritmo es un conjunto de pasos ordenados y finitos que permiten resolver un problema o realizar una tarea específica. En programación, un algoritmo se traduce en código que sigue esa lógica paso a paso.*

7.📘 Ejemplo
MRUV (Movimiento Rectilíneo Uniformemente Variado)
Supongamos que queremos resolver el siguiente problema de MRUV:

**Una partícula parte del reposo y se mueve con una aceleración constante de**
$a=2m/s^2$
* ¿Qué distancia recorre en 5 segundos?

Sabemos que en MRUV, si parte del reposo, usamos la fórmula:$$x=\frac{1}{2} a t^{2}$$
Sol.

✅ Algoritmo en lenguaje natural:

* Leer o definir la aceleración a.

* Leer o definir el tiempo t.

* Calcular la distancia usando la fórmula.

* Mostrar el resultado.
"""

# Paso 1: Definir los datos
a = 2  # aceleración en m/s^2
t = 5  # tiempo en segundos

# Paso 2: Aplicar la fórmula del MRUV
x = 0.5 * a * t**2

# Paso 3: Mostrar el resultado
print(f"La distancia recorrida en {t} segundos es {x} metros.")

"""### 🔹 TEMA 3: FUNCIONES EN PYTHON
**🧠 ¿Qué es una función?**

Una función es un bloque de código reutilizable que realiza una tarea específica. En física, puede representar fórmulas o modelos físicos que usamos varias veces.

✅ ¿Por qué usar funciones?
Te ayudan a organizar el código.

Evitan repetir lo mismo muchas veces.

Permiten reutilizar fórmulas con diferentes datos.

Hacen que tu código sea más limpio y fácil de entender.

###🧱 ESTRUCTURA DE UNA FUNCIÓN EN PYTHON
`def nombre_funcion(parametros):
    # Cuerpo de la función
    return resultado
`
"""

#esta es la funcion
def energia_cinetica(masa, velocidad):
    return 0.5 * masa * velocidad**

#lladama a funcion
Ec = energia_cinetica(10, 5)
print(Ec)

"""###🧰 PALABRAS CLAVE IMPORTANTES

| Palabra clave | Uso en funciones                  |
| -------------- | -------------------------------- |
| def            | Define una función                |
| return         | Devuelve un resultado              |
| input()        | Obtener datos del usuario (opcional) |
| print()        | Mostrar datos en pantalla         |

##🧪 TIPOS DE FUNCIONES
1. 📥 Con parámetros y retorno
python
"""

def volumen_cilindro(radio, altura):
    return 3.1416 * radio**2 * altura

"""2. 📥 Con parámetros pero sin retorno (solo imprime)"""

def mostrar_datos(masa, velocidad):
    print(f"La masa es {masa} kg y la velocidad es {velocidad} m/s")

"""3. 📤 Sin parámetros, con retorno"""

def constante_gravedad():
    return 9.81

"""4. ⚙️ Funciones auxiliares (usadas dentro de otras)"""

def cuadrado(x):
    return x * x

def energia_cinetica(m, v):
    return 0.5 * m * cuadrado(v)

"""## 🧪EJERCICIOS CON FUNCIONES

1. Crear una función que calcule la energía cinética:$$Ec = \frac{1}{2} ⋅ m ⋅ v²$$
si la masa es de 5 kg y la velocidad es 6 m/s
"""

#hago mis variables, segun los datos que me dan
m=5
v=6
#tengo mi funcion
def energia_cinetica(masa, velocidad):
    return 0.5 * masa * velocidad**2

#llamo a mi funcion, y reemplazo los valores
Ec = energia_cinetica(5, 6)
print("la energia cinetica es:", Ec)

"""2. Función para calcular el área de un triángulo:
$$A=\frac{b\cdot h}{2}$$
Las altura h= 3 [m] y la base es de 5 [m]
"""

# hago mi funcion
def area_tri(base, altura):
    return (base * altura) / 2

# declaro mis variables
b = 3
h = 5
A = area_tri(b, h)
print("El área del triángulo es de:", A)

"""3. Función que convierta kilómetros a metros.

"""

def con_km(x):
    return x/1000

metros= 25000
km = con_km(metros)
print(km,"[Km]")

"""4. Función para calcular la velocidad final en MRUA:
$$v_f=v_i +a \cdot t$$
con v_i=10 m/s; a=-9 m/s2; time= 890 s
"""

def vel_f(veloini, acel,time):
    return veloini+acel*time

vi=10
ac=-9
ti=890
vf=vel_f(vi,ac,ti)
print(vf)